version: "3"
services:
  dispatcher_author:
    build: .
    container_name: test_dispatcher_author
    environment:
      - RENDERER_HOST=test_dispatcher_renderer
      - RENDERER_PORT=80
      - DISPATCHER_CONFIG=author
      - DISPATCHER_LOGLEVEL=${DISPATCHER_LOGLEVEL}
    ports:
      - ${DISPATCHER_PORT_AUTHOR}:8080
    links:
      - nginx
    networks:
      - backend
  dispatcher_publish:
    build: .
    container_name: test_dispatcher_publish
    environment:
      - RENDERER_HOST=test_dispatcher_renderer
      - RENDERER_PORT=80
      - DISPATCHER_CONFIG=publish
      - DISPATCHER_LOGLEVEL=${DISPATCHER_LOGLEVEL}
    ports:
      - ${DISPATCHER_PORT_PUBLISH}:8080
    links:
      - nginx
    networks:
      - backend
  nginx:
    image: aemdesign/nginx
    container_name: test_dispatcher_renderer
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
