version: "3"
services:
  dispatcher:
    build: .
    container_name: test_dispatcher
    environment:
      - RENDERER_HOST=test_dispatcher_renderer
      - RENDERER_PORT=80
      - DISPATCHER_CONFIG=${DISPATCHER_CONFIG}
      - DISPATCHER_LOGLEVEL=${DISPATCHER_LOGLEVEL}
    ports:
      - ${DISPATCHER_PORT}:8080
    links:
      - nginx
    networks:
      - backend
  nginx:
    image: aemdesign/nginx
    container_name: test_dispatcher_renderer
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
